---

- name: Update Apt
  apt:
          update_cache: true

- name: Intall required packages
  apt:
          pkg:
                  - php-curl
                  - php-gd
                  - php-intl
                  - php-mbstring
                  - php-soap
                  - php-xml
                  - php-xmlrpc
                  - php-zip
          state: latest
          update_cache: true

- name: Install php-fpm
  apt:
          name: php-fpm
          state: latest
          update_cache: true

- name: Install php-mysql
  apt:
          name: php-mysql
          state: latest
          update_cache: true

- name: Restart php-fpm service
  systemd:
          state: restarted
          daemon_reload: yes
          name: php7.3-fpm


