---

- name: Install UFW
  apt:
          name: ufw
          state: latest
          update_cache: true

- name: Configure UFW for Nginx
  community.general.ufw:
          rule: allow
          port: "80"
          proto: tcp

- name: Open OpenSSH port
  community.general.ufw:
          rule: allow
          name: OpenSSH

- name: Install Nginx
  apt:
          name: nginx
          state: present
          update_cache: true

- name: Start Nginx service
  systemd:
          state: started
          name: nginx.service

- name: Make directory for your site
  file:
          path: "/var/www/{{  your_domain  }}"
          owner: "www-data"
          group: "www-data"
          state: directory
          mode: "755"

- name: Create file for our site
  template:
          src: "files/site.conf.j2"
          dest: "/etc/nginx/sites-available/{{  your_domain  }}"

- name: Enable new site (creatink symbolik link from sites-available to sites-enabled
  file:
          src: "/etc/nginx/sites-available/{{  your_domain  }}"
          dest: "/etc/nginx/sites-enabled/{{  your_domain  }}"
          state: link
          
- name: Sets Up PHP Info Page
  template:
             src: "files/info.php.j2"
             dest: "/var/www/{{  your_domain  }}/info.php"

- name: Reload Nginx
  service:
          name: nginx
          state: reloaded

- name: Restart Nginx
  service:
          name: nginx
          state: restarted
