---

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
         src: https://wordpress.org/latest.tar.gz
         dest: "/var/www/{{  your_domain  }}"
         remote_src: yes  
         creates: "/var/www/{{  your_domain  }}/wordpress"

- name: Removing default Wordpress-configuration file
  file:
          path: "/var/www/{{  your_domain  }}wordpress/wp-config-sample.php"
          state: absent

- name: Using our Wordpress template-file and copying it in to Wordpress directory
  template:
          src: "files/wp-config.php.j2"
          dest: "/var/www/{{  your_domain  }}/wordpress/wp-config.php"

- name: Set ownership
  file:
        path: "/var/www/{{  your_domain   }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
